---
title: "pSSD_ToMEx2"
author: "Scott Coffin"
date: "`r Sys.Date()`"
output:
  html_document:
    code_folding: hide
    theme: journal
    toc: yes
    toc_float: yes
    toc_depth: 6
    number_sections: true
  word_document:
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.width=10, fig.height=8, fig.path='output/figures',
                      warning=FALSE, message=FALSE,time_it = TRUE) 
```

# Probabilistic Species Sensitivity Distribution Plus

The below code will not run with an open environment due to memory constraints.
```{r eval=FALSE, include=FALSE}
#library(gdata)
#keep(tier1_2_large, sure = TRUE)
write.csv(tier1_2_large, "tier1_2_large.csv")
#rm(list = ls())
#gc()
tier1_2_large <- read.csv("tier1_2_large.csv")
```

```{r eval=FALSE, include=FALSE}
# -------------------------------------------------------------------------------------------------
# Code based on PSSD and PNEC calculations using the tool PSSD+ developed by Wigger et al. (2019)
# -------------------------------------------------------------------------------------------------
# 
# Associated publication: Systematic consideration of parameter uncertainty and variability in
#                         probabilistic species sensitivity distributions
# 
# Authors: Henning Wigger, Delphine Kawecki, Bernd Nowack and V?ronique Adam
# 
# Institute: Empa, Swiss Federal Laboratories for Materials Science and Technology,
#            Technology and Society Laboratory, Lerchenfeldstrasse 5, 9014 St. Gallen, Switzerland
# 
# submitted to Integrated Environmental Assessment and Management in December 2018
# 
# -------------------------------------------------------------------------------------------------

##### Build functions ####
source("PSSD/rmore.r")
source("PSSD/do.pssd.r")
#source("PSSD/do.pssd.troph.r")
#source("PSSD/do.pssd.ag.r")


###################################################################################################
##### MAIN PARAMETERS FOR THE CALCULATION #########################################################
###################################################################################################

# number of simulations for the triangular distributions of the data points and uncertainty factors
SIM <- 10 #10 is minimum, 10,000 is recommended

# coefficient of variation for the data point distributions
CV.DP <- 0.3

# coefficient of variation for the uncertainty factor distributions
CV.UF <- 0.5
```
## Data preparation
```{r eval=FALSE, include=FALSE}
memory.limit(size=56000) #force R to use more memory than what's phyiscally available
library(reshape2)
require(tidyverse)
require(Matrix)

t2 <- tier1_2_large#%>% 
 # filter(species == "magna")

# prep dataframe for tox datapoints
DP_1_large_volume <-  t2 %>% 
  #mutate(tier = "A") %>% 
  mutate(id = row_number()) %>% 
  mutate(particles_L = EC_env_v.particles.mL * 1000) %>% #must *10 to eliminate sub-zero values, can't go above 10 b/c R can't handle integers above certain value
  mutate(particles_L_round = as.integer(round(particles_L,digits = 1))) %>%  #must make integer for below code to work
  select(id, species, particles_L_round) %>% 
  acast(id ~ species, value.var = "particles_L_round") %>% 
  Matrix(sparse = TRUE) # makes a smaller object than using as.matrix()

#prep uncertainty factors for conversion from acute to chronic values
UFt_1_large_volume <- t2 %>% 
  mutate(id = row_number()) %>% 
  select(id, species, af.time) %>% 
  acast(id ~ species, value.var = "af.time")

# uncertainty factors for conversion of dose descriptors to NOEC
UFdd_1_large_volume <- t2 %>% 
  mutate(id = row_number()) %>% 
  select(id, species, af.noec) %>% 
  acast(id ~ species, value.var = "af.noec")
#rm(tier1_2_large)
```

## Tier 1_2_Large_volume
```{r eval=FALSE, include=FALSE}
# read toxicity data
# data points from the literature
DP   <- DP_1_large_volume
# uncertainty factors for conversion from acute to chronic values
UFt  <- UFt_1_large_volume
# uncertainty factors for conversion of dose descriptors to NOEC
UFdd <- UFdd_1_large_volume


###################################################################################################
##### CALCULATION OF NOECs and PSSDs ##############################################################
###################################################################################################

# estimate the NOEC distributions for each species
NOEC_t1_volume <- do.pSSD(DP, UFt, UFdd, SIM, CV.DP, CV.UF)

# calculate the deterministic (modal) values of the NOEC
NOEC.det_t1_volume <- DP/(UFdd*UFt)

###convert to particles/L
NOEC2_t1_volume = NOEC_t1_volume * 1000 #correction factor from getting into integer values (above)
NOEC.det2_t1_volume = NOEC.det_t1_volume * 1000
```

```{r eval=FALSE, include=FALSE}
###################################################################################################
##### EXAMPLES OF RESULTS #########################################################################
###################################################################################################

### Plot the probability densities of some species

## For a species with 1 endpoint (T. thermophila)
# histogram
hist(log10(NOEC2_t1_volume[3,]), freq = F, main = "Ceriodaphnia dupia - 14 endpoints", xlab = "NOEC log[particles/L]")
# probability density
lines(density(log10(NOEC2_t1_volume[3,])), col = "red", lwd = 2) 
# Deterministic NOEC
abline(v = median(log10(NOEC.det2_t1_volume[,3]), na.rm = TRUE), col = "green", lty = 2, lwd = 2)
```

```{r eval=FALSE, include=FALSE}
## For a species with 1 endpoints (Danio rerio)
hist(NOEC_t1_volume[11,], freq = F, main = "Danio rero - 1 endpoints", xlab = "NOEC [ug/l]")
lines(density(NOEC_t1_volume[11,]), col = "red", lwd = 2)
abline(v = median(NOEC.det_t1_volume[,11], na.rm = TRUE), col = "green", lty = 2, lwd = 2)

# for(i in 1:length(which(!is.na(NOEC.det[,11])))){
#   abline(v = NOEC.det[i,11], col = "green", lty = 2, lwd = 2)
#}

```

```{r eval=FALSE, include=FALSE}
### Plot PSSDs

# calculate all PSSD curves
xvalues <- seq(-6,7,0.001)
PSSD <- matrix(NA, SIM, length(xvalues))
# calculate the ecdf function
for(i in 1:SIM){
  the.ecdf.f <- ecdf(log(NOEC_t1_volume[,i], base = 10))
  PSSD[i,] <- the.ecdf.f(xvalues)
}

```

```{r eval=FALSE, include=FALSE}
# Plot the mean PSSD
plot(c(-2,6), c(0,1),
     main = "Microplastics Probabilistic SSD (1-5,000 um; volumetric)",
     xlab = "NOEC [particles/L]",
     ylab = "Proportion of Species Affected",
     type = "n",
     axes = F)
axis(1, at = c(-2,0,2,4,6), labels = expression(10^-2, 10^0, 10^2, 10^4, 10^6), lwd = 0.5)
axis(2, lwd = 0.5, las = 1)
abline(h = seq(0,1,0.2), lty = 1, lwd = 0.5, col = "gray90")
abline(v = seq(-6,5,1), lty = 1, lwd = 0.5, col = "gray90")
box(lwd = 0.5)
lines(xvalues, apply(PSSD,2,function(x) {mean(x)}), col = "red", lwd = 1.5)
legend("topleft", "Mean PSSD", col = "red", lwd = 1.5)
```

## Tier 1_2_Small_SurfaceArea
```{r eval=FALSE, include=FALSE}
t2_s <- tier1_2_small#%>% 
 # filter(species == "magna")

# prep dataframe for tox datapoints
DP_1_small_surfaceArea <-  t2_s %>% 
  #mutate(tier = "A") %>% 
  mutate(id = row_number()) %>% 
  mutate(particles_L = EC_env_sa.particles.mL * 1000) %>% #must *10 to eliminate sub-zero values, can't go above 10 b/c R can't handle integers above certain value
  mutate(particles_L_round = as.integer(round(particles_L,digits = 1))) %>%  #must make integer for below code to work
  select(id, species, particles_L_round) %>% 
  acast(id ~ species, value.var = "particles_L_round") %>% 
  Matrix(sparse = TRUE) # makes a smaller object than using as.matrix()

#prep uncertainty factors for conversion from acute to chronic values
UFt_1_small_surfaceArea <- t2_s %>% 
  mutate(id = row_number()) %>% 
  select(id, species, af.time) %>% 
  acast(id ~ species, value.var = "af.time")

# uncertainty factors for conversion of dose descriptors to NOEC
UFdd_1_small_surfaceArea <- t2_s %>% 
  mutate(id = row_number()) %>% 
  select(id, species, af.noec) %>% 
  acast(id ~ species, value.var = "af.noec")

# read toxicity data
# data points from the literature
DP   <- DP_1_small_surfaceArea
# uncertainty factors for conversion from acute to chronic values
UFt  <- UFt_1_small_surfaceArea
# uncertainty factors for conversion of dose descriptors to NOEC
UFdd <- UFdd_1_small_surfaceArea


###################################################################################################
##### CALCULATION OF NOECs and PSSDs ##############################################################
###################################################################################################

# estimate the NOEC distributions for each species
NOEC_t1_SA <- do.pSSD(DP, UFt, UFdd, SIM, CV.DP, CV.UF)

# calculate the deterministic (modal) values of the NOEC
NOEC.det_t1_SA <- DP/(UFdd*UFt)

###convert to particles/L
NOEC2_t1_SA = NOEC_t1_SA * 1000 #correction factor from getting into integer values (above)
NOEC.det2_t1_SA = NOEC.det_t1_SA * 1000
```

## Plotting
```{r eval=FALSE, include=FALSE}
# calculate PNEC (HC5) for volume and surface area
PNEC_t1_SA <- apply(NOEC_t1_SA,2,function(x){quantile(x, probs = 0.05, na.rm = TRUE) })

PNEC_t1_volume <- apply(NOEC_t1_SA,2,function(x){quantile(x, probs = 0.05, na.rm = TRUE) })

#make into dataframe
PNECs <- data.frame( = PNEC_t1_SA,
                    

PNEC %>% 
  data.frame(PNEC) %>% 
  ggplot(aes(x = PNEC))
```

