#' ToMEx 2.0 ecotoxicity dataset
#'
#' Microplastics ecotoxicity records used throughout the PSSD++ workflow.
#' Data are bundled as a plain data frame identical to the source RDS shipped
#' in `inst/extdata/aoc_z_tomex2.RDS`.
#'
#' @format A data frame with the fields described in the ToMEx 2.0 metadata.
#' @usage data(tomex2)
"tomex2"

#' Minimal ToMEx 2.0 subset for fast testing and examples
#'
#' A 218-row subset of \code{\link{tomex2}} containing 5 freshwater and 5
#' marine species (\emph{Daphnia magna}, \emph{Hyalella azteca},
#' \emph{Ceriodaphnia dubia}, \emph{Danio rerio}, \emph{Oncorhynchus mykiss},
#' \emph{Paracentrotus lividus}, \emph{Artemia franciscana},
#' \emph{Parvocalanus crassirostris}, \emph{Brachionus plicatilis}, and
#' \emph{Mytilus galloprovincialis}).  All rows pass the Tier 1–4 quality
#' filters applied in \code{\link{run_pssd_reprex}}.
#'
#' Intended for \code{\\dontrun} examples and interactive exploration without
#' the computational cost of the full dataset.
#'
#' @format A data frame with 218 rows and 177 columns (identical structure to
#'   \code{\link{tomex2}}).
#' @usage data(tomex2_mini)
#' @seealso \code{\link{tomex2}} for the full dataset,
#'   \code{\link{matrix_function}} and \code{\link{MC_sim_align_parallel}} for
#'   how to use this in the workflow.
#' @source Subset of \code{\link{tomex2}}; regenerated by
#'   \code{data-raw/create_tomex2_mini.R}.
"tomex2_mini"

#' Default alignment parameters (means and SDs)
#'
#' Vectorized defaults for the Monte Carlo alignment sampler
#' (\link[=matrix_function]{matrix_function()}), providing means and standard deviations for length/width
#' ratios, densities, alpha parameters, height:width ratios, translocation size
#' limit, and body-length model coefficients.
#'
#' @format A data frame of parameter means and standard deviations.
#' @usage data(param_default_values)
#' @export
"param_default_values"
